; ====================================================================
; Asterisk HTTP Server Configuration for WebRTC / WebSocket
; ====================================================================

[general]
enabled=yes
bindaddr=0.0.0.0
bindport=8089
tlsenable=no
; Traefik o Nginx / Cloudflare maneja el certificado SSL (WSS) externamente
; y reenvía el tráfico WebSocket a este puerto 8089.
session_inactivity=30000
session_keep_alive=15000
